BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Role] DROP CONSTRAINT [Role_id_df];
ALTER TABLE [dbo].[Role] ADD CONSTRAINT [Role_id_df] DEFAULT (newid()) FOR [id];

-- AlterTable
ALTER TABLE [dbo].[User] DROP CONSTRAINT [User_id_df];
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_id_df] DEFAULT (newid()) FOR [id];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
